### ISSUE TITLE
Part of log message removed

### ISSUE THREAD

**Issue by michaeljmx** [camitz/CloudWatchAppender#13]
We have a problem with the appender removing part of log text including "Message:" and word after it. For example if text "Message: sample text for logging" is logged, only text "text for logging" is sent to CloudWatch.

It seems that the issue is related to the way the appender processes tokens. However, I found no way to disable token recognition and preventing changing text. Is there way to do it, or could you add this functionality? We just need to send the text we specified to CloudWatch without any changes.

**Comment by camitz** [comment]
Correct functionality ought to include at least "sample". I'll check it
out.

Just to be clear, in your use case, did you actually want to include
"Message: ", or not?

**Comment by michaeljmx** [comment]
We want to include "Message:" too. Actually we don't use tokens and want to keep logged text completely unchanged.

**Comment by camitz** [comment]
Sorry for the delay!

I've confirmed this as an issue. Message, GroupName, StreamName and Timestamp are all reserved keywords for the parser associated with the logs appender. The parser is unfortunately not configurable or replacable...

...yet. However I think it would be a good idea, so I'll go ahead and implement it.

So, I'll get back to you when I do. In the mean time you can just put "Mesage:" instead and pretend it's a misspelling. ;)

**Comment by michaeljmx** [comment]
Thank you very much for the reply, I'll look forward for the option to be implemented.
At the moment I've set our system to replace "Message:" in logged text with "Message :" (with space inserted before the colon), but I want my logs to be perfect :)

**Comment by camitz** [comment]
I can definitely sympathize! :)

**Comment by camitz** [comment]
I've release v4.5-alpha. Put this in your config:

    <appender name="CloudWatchLogsAppender" type="CloudWatchAppender.BufferingCloudWatchLogsAppender, CloudWatchAppender">
      //Other config here...
      <eventMessageParser type="CloudWatchAppender.Parsers.DummyLogsEventMessageParser"/>        
    </appender>

**Comment by michaeljmx** [comment]
Thank you very much! When to you expect to publish it in NuGet?

**Comment by camitz** [comment]
Version 4.5.2 is on nuget. It's marked stable unfortunately although it's
not!

**Comment by camitz** [comment]
I just pushed v.4.6.0-alpha1 to nuget.
