### ISSUE TITLE
Configurable Culture Info

### ISSUE THREAD

**Issue by ereznassimi** [camitz/CloudWatchAppender#15]
I have noticed the following line of code in **CloudWatchAppender/CloudWatchAppender/Services/CloudWatchClientWrapperBase.cs** line 127:

_**Thread.CurrentThread.CurrentCulture = new CultureInfo("en-GB", false);**_

Can you make it a configurable parameter?

Thank you!

**Comment by camitz** [comment]
For what purpose? I think it's a work-around for a bug in the aws-lib
that's been fixed. I think a better idea is to remove it completely.

**Comment by ereznassimi** [comment]
OK. I assumed that it has impact on component. If it can be removed, then definitely!
