### ISSUE TITLE
Update AWS SDK? 

### ISSUE THREAD

**Issue by asherber** [camitz/CloudWatchAppender#16]
Are there any plans to update to v3 of the SDK? We'd like to use this appender in some new development work where we're using v3, and the two versions don't seem to play nicely together.

**Comment by asherber** [comment]
Turns out there were only a few changes needed to make this code compatible with v3. I submitted a pull request.

**Comment by camitz** [comment]
Wonderful! I'm concerned about some of the changes but I admit it looks easier than I would have thought.

**Comment by asherber** [comment]
The only substantive changes were in `CloudWatchClientWrapperBase.cs`, where the `AWSClientFactory` was removed. I took what seemed to be the quickest route to get this to work, but of course you may prefer a different approach.

**Comment by camitz** [comment]
What about the removal of the UserAgent setter? What consequences will that have?

**Comment by asherber** [comment]
Since `UserAgent` is intended to show the the app or library making the call, it makes sense for Amazon to set this explicitly in their assembly and make the property read-only. I doubt that anyone using your appender has actually written code to change this string, but I suppose this would be a minor breaking change for anyone who has.

**Comment by camitz** [comment]
You're probably right.

**Comment by camitz** [comment]
I just released this as a beta on nuget. If your before mentioned integration tests pass then I'll put it in production.

**Comment by asherber** [comment]
Thanks! We have been using my fork all week in our dev sandbox, writing to CloudWatch Logs with no problem. (We don't currently use metrics.)

I admit that I have not been able to get the `BufferedLogsAppender` to work in your sample project,with group and stream names specified either in the message or in the `LogDatum`, but I couldn't get them to work before I switched to v3 either. I probably have some combination of config items wrong. (I've tried `configOverrides` both true and false, and the `groupName` and `streamName` both set and unset in the config.)

**Comment by camitz** [comment]
Yeah I noticed some of them were a bit off, I fixed them in this major overhaul I've been working on for the past couple of days.

I'll go to production then.

Keep an eye out for version 5! I've done what Amazon did so you would only need to include the CloudWatch Logs lib and a core lib. Also added SNS and SQS.

**Comment by camitz** [comment]
Thanks for your contribution!

**Comment by asherber** [comment]
Great, thanks very much! I'm happy to lend a hand.

**Comment by asherber** [comment]
4.7.0.1-beta on NuGet was SDK v3, but 4.7.0.5 is back to SDK v2.

**Comment by camitz** [comment]
Really? Ok, I'll fix it.
