### ISSUE TITLE
LogsAppender doesn't like dashes in group/stream names

### ISSUE THREAD

**Issue by asherber** [camitz/CloudWatchAppender#18]
Using latest master from GitHub.

If I have a group name or stream name with a dash, like `foo-bar`, the appender seems to use only the first part and tries to put the second part in the message.

This happens whether I use a `LogDatum` or whether I use the embedded syntax: 

``` csharp
log.Info("A tick!" Groupname: foo-bar);
```

**Comment by asherber** [comment]
Is the parser using `\w` to identify words? I believe group and stream names can also include hyphens, slashes, and periods, which are not captured by `\w`.

**Comment by camitz** [comment]
You are quite right.

**Comment by camitz** [comment]
Now using 

     [^()}{"", ]

instead of

     \w

This passes:

            Assert.That(new LogsEventMessageParser()
                .Parse("StreamName: \"New Name\" A tick! GroupName: f-o_o/b.a.–r")
                .Select(x => x.GroupName), 
                Has.All.EqualTo("f-o_o/b.a.–r"));

This fix will be available in version 5.1.

**Comment by asherber** [comment]
Thanks!
