### ISSUE TITLE
LogDatumRenderer chokes on null Timestamp

### ISSUE THREAD

**Issue by asherber** [camitz/CloudWatchAppender#19]
`LogDatum.Timestamp` is nullable, but `LogDatumRenderer.RenderAppenderLogDatum` has:

``` csharp
if (logDatum.Timestamp != default(DateTime))
   writer.Write("Timestamp: {0}, ", logDatum.Timestamp.Value.ToString(CultureInfo.CurrentCulture))
```

This will throw an exception if `Timestamp` has not been assigned a value. 

If `Timestamp` needs to be nullable, then I think the first line above should be:

``` csharp
if (logDatum.Timestamp.HasValue() && logDatum.Timestamp != default(DateTime))
```

Otherwise perhaps Timestamp could be a non-nullable `DateTime`.

**Comment by camitz** [comment]
A fix will be in version 5.1.
