### ISSUE TITLE
Make LogEventProcessor pluggable?

### ISSUE THREAD

**Issue by asherber** [camitz/CloudWatchAppender#21]
Is it possible to make `LogEventProcessor` pluggable in `BufferingCloudWatchLogsAppender`, as you have done with the `EventMessageParser`?

My application has a very defined workflow, and the appender will always be getting a populated `LogDatum`, with the message, group name, and stream name exactly as I want them. What I want to avoid is the round trip from `LogDatum` to rendered string and back to `LogDatum`, because I can't guarantee that the message won't contain the token `message:`. 

What I'd like to do is plug in my own `LogEventProcessor`, with an overridden `ProcessEvent()` that looks something like this:

``` csharp
public IEnumerable<LogDatum> ProcessEvent(LoggingEvent loggingEvent, string renderedString)
{
   return new [] { (LogDatum)loggingEvent.MessageObject };
}
```

**Comment by asherber** [comment]
Alternatively, could you make more of the `private` fields and methods in `BufferingCloudWatchAppender` `protected`, so that I can access them from a descendant class?

I could accomplish the same aim as above by overriding `SendBuffer()` so that it doesn't call the `LogEventProcessor` at all, except that I don't currently have access to `Assemble()` or `_client`.

**Comment by camitz** [comment]
I though about making the EventProcessor pluggable when I was working on the 5.0 update. It seems the right direction to go.

**Comment by asherber** [comment]
Here's another approach that accomplishes what I'm looking for. I'm not sure which is preferable from a design point of view.

In `BufferingCloudWatchLogsAppender.cs`:

```csharp
protected virtual IEnumerable<LogDatum> ProduceLogData(LoggingEvent[] events)
{
    var data = events.SelectMany(e => _eventProcessor.ProcessEvent(e, RenderLoggingEvent(e)).Select(r => r));
    return data;
}

protected override void SendBuffer(LoggingEvent[] events)
{
    var rs = ProduceLogData(events);

    var requests = Assemble(rs);

    foreach (var putLogEventsRequest in requests)
        _client.AddLogRequest(putLogEventsRequest);
}
```

Now I can override `ProduceLogData()` to do whatever I want – including channeling events to my own `LogEventProcessor` if needed. (In my case, I can just return the `event.MesssageObject` as `LogDatum`, no processor needed.)

**Comment by camitz** [comment]
I might do both.

**Comment by camitz** [comment]
There is a new commit. I haven't had time to try it out. Please do if you get the chance.

Making the EventProcessors pluggable turned out difficult having to do with idempotency - they're supposed to be created at use. What I'll probably do is make the _type_ pluggable but then I'll need to find the best constructor to use and cache the selection.

But I followed your other suggestion.
