### ISSUE TITLE
Missing assembly?

### ISSUE THREAD

**Issue by MadTigger** [camitz/CloudWatchAppender#22]
I down loaded this project to see how it was hooking into AWS, and after restoring the NuGet packages it would not build. It looks like you have an assembly refrence in various .csproj files to an assembly that isn't checked in or isn't linked to a NuGetPackage:

    <Analyzer Include="packages\AWSSDK.CloudWatchLogs.3.1.2.4\analyzers\dotnet\cs\AWSSDK.CloudWatchLogs.CodeAnalysis.dll" />

After removing all these references, everything seems to build fine.

**Comment by camitz** [comment]
Thanks for spotting this!
