### ISSUE TITLE
Cannot recover instance-id

### ISSUE THREAD

**Issue by pontili-xpeppers** [camitz/CloudWatchAppender#4]
I configured your appender in this way

    <dimension type="Amazon.CloudWatch.Model.Dimension">
        <name value="InstanceID"/>
        <value value="%metadata{instanceid}"/>
    </dimension>

But when I launch my application I always have this error
log4net:ERROR XmlHierarchyConfigurator: Cannot find Property [dimension] to set
object on [CloudWatchAppender.BufferingCloudWatchLogsAppender]

And of course in the logs I read NoIstanceId

**Comment by camitz** [comment]
Hi!

Thanks for your interest in the CloudWatchAppender project. 

Neither of the two CloudWatchLogs-appenders support dimensions. Only CloudWatchAppender and BufferingsCloudWatchAppender do.

See http://docs.aws.amazon.com/AmazonCloudWatch/latest/DeveloperGuide/WhatIsCloudWatchLogs.html

All the best,
Martin
