### ISSUE TITLE
Add getters to StreamName on BufferingCloudWatchLogsAppender

### ISSUE THREAD

**Issue by JoeRall** [camitz/CloudWatchAppender#5]
@camitz Great work on this project. We just started using your appender and it's been a breeze. Currently we've derived from your [BufferingCloudWatchLogsAppender](https://github.com/camitz/CloudWatchAppender/blob/33ec1f5184f20852c20f513c0247f7ef29bc389f/CloudWatchAppender/BufferingCloudWatchLogsAppender.cs#L97) and doing some custom logic inside of ActivateOptions for reasons that are out of the scope of this thread. But we'd like to make sure that we have a valid StreamName specified in the app config but currently that property is only a Setter. Do you think you could add the getters to that property (and I guess all of the other ones). Granted this might be a weird use case, but I figured I'd at least mention it to you instead of forking your project and doing it on my own. Give back to the community right? 

I don't think this request should have any side effects, but I could be wrong. I can submit a pull request if you approve. 

Thanks for your time.

**Comment by camitz** [comment]
@JoeRall I'm thrilled that you like the project and hearing that it's easy to use!

I have no objections at all to your suggestion. And I'd love to show off some other other developers involved in the project. So go right ahead and submit a pull request.

If you can leave getters out of the interfaces without breaking your use case then I suppose that would be cleaner. If you can't, I seriously don't mind.

Have a good weekend!

**Comment by JoeRall** [comment]
@camitz Sounds great. For my use I have no need to alter the interfaces. To keep things clean I'll just make them protected instead of public. 

I'm on the train now. I'll try to submit a pull request this afternoon. 

Thanks for letting me be a part of the project :)

**Comment by camitz** [comment]
@JoeRall Absolutely! Looking forward to your commit :)

**Comment by JoeRall** [comment]
@camitz Thanks so much for accepting the pulls and closing out the ticket. I hate to be a pain but do you think you'd be able to update the [Nuget](https://www.nuget.org/packages/CloudWatchAppender/) package as well? :smile:

**Comment by camitz** [comment]
@JoeRall No problem, at all. Still excited about your contribution! I was going to take the opportunity to update the AWS lib, so I'll just do some quick research into that. I'll let you know when I'm done.

**Comment by JoeRall** [comment]
@camitz Sounds great! Can't wait. If you need help with anything else, just let me know!

**Comment by camitz** [comment]
I just published 4.3.3 on Nuget.

Here are some thoughts, let me know if you think anything is awry.

I deem the solution to be stable enough to remove the beta-descriptor. Two people using it in production ought to be enough for a project of this size.

I am reluctant to upgrade to the latest 2.X version AWSSDK for two reasons. 

1. While, I have found at least one dependency deprecated, I haven't found anything breaking, I can't at this point, for other reasons, put the new version in production, which I want to do before releasing anything. If you want to try, I encourage you to do so, but...

2. The point of the upgrade would be to keep deployment small for users dependent on a later 2.X version. They can do that anyway plus, if this was a big priority then the best return for effort would probably be given by upgrading to version 3, which boast separate libs per service.

Oh, and I made you collaborator.

**Comment by JoeRall** [comment]
@camitz Thanks for making me a contributor to this project! I really appreciate it. And I think you're right for removing the beta-descriptor! As for upgrading the AWSSDK dependency, here's my thoughts.

If there's no pressing reason to upgrade then lets not do that. It looks like the version we're using is from Jan of 2015 and there's only been minor revisions since then. And since our dependency is >= 2.3.15 then if someone wants to run the latest version of the AWSSDK, they can do so. 

If Amazon updates to 2.4.x, then we might want to consider updating the project because there could be breaking changes with the API. Luckily, Nuget will always keep our old versions, so you should never worry about breaking other peoples code, because they can always just link against the version of this project that works for them. Plus it's open source, so they can always download the bits.

Thanks for pushing out the updated Nuget package. I really appreciate it. Also, linking to this issue as the release notes is actually a pretty slick idea. I'll have to remember that!

**Comment by camitz** [comment]
That sounds reasonable thinking. 

Happy coding!

**Comment by JoeRall** [comment]
@camitz 

Hey I finally had a chance to upgrade CloudWatchAppender to the latest (4.3.4) but the dlls are still on version 4.3.2 and don't contain my latest changes (i.e. Stream Name getters). Did I submit my pull request wrong or something?

**Comment by JoeRall** [comment]
@camitz  - If you want, we can leverage [Cool Whip](https://github.com/MasterDevs/CoolWhip) to automate builds and publishing nuget packages using AppVeyor. It's pretty cool. Basically once it's setup, you create a release inside of GitHub, and then the project is built and deployed to nuget.

**Comment by camitz** [comment]
Sounds awesome! Never heard of either till now. Do you mind if I start and you take over? I like to try new technology out hands on.

**Comment by JoeRall** [comment]
@camitz - Sure. That'd actually be a great test for us to see how well that project is. Let me know if you have any questions. Now we can show a shiny badge on our [README.md](https://github.com/camitz/CloudWatchAppender/blob/master/README.md) file showing a clean build!

**Comment by jquintus** [comment]
Hey, writer of CoolWhip over here.  If you have any questions or problems setting it up let me know and I'll help out.

**Comment by JoeRall** [comment]
@camitz - Hey, just checking in. Any luck publishing the latest version to nuget?

**Comment by camitz** [comment]
Hey Joe!
I'm a little slow on the coolwhip and appveyor, if that's what you mean. Nothing's happened since the last nuget commit, has it?

**Comment by JoeRall** [comment]
@camitz No worries. Nothing has happened with the last nuget commit, but the latest nuget build doesn't contain the changes with this pull request. So I was wondering if you could publish a new nuget package with these changes. If you do it with Cool Whip / App Veyor great, if not, could you just do it with your normal process?

Sorry to be a pain but we're really excited to use this :smile:

**Comment by camitz** [comment]
Ah, ok, that was not intentional! I'll try again.

**Comment by JoeRall** [comment]
@camitz - No worries at all!

**Comment by camitz** [comment]
There, published! Please check!

**Comment by JoeRall** [comment]
@camitz - I'm sorry. But the change still isn't reflected. Are you sure you pulled in my latest changes locally? I looked at both the 3.5 & 4.5 dlls and both show the following:

![image](https://cloud.githubusercontent.com/assets/1762141/11370737/12b73d82-9293-11e5-96d8-09474847fa8c.png)

Yet you should see the following 

```c#
        public string StreamName
        {
            set
            {
                _streamName = value;
                _eventProcessor = null;
            }
            get { return _streamName; }
        }
```

Source: 
https://github.com/camitz/CloudWatchAppender/blob/master/CloudWatchAppender/BufferingCloudWatchLogsAppender.cs#L61-L69

**Comment by camitz** [comment]
I see the same and I'm baffled.

screw that, let's work together on getting coolwhip into the project.
(Didn't realize this was your baby.)

I already started and I've created an account at appveyor. I'm not
immediately sure how this will work given there are multiple projects but
maybe I'll find out.

**Comment by JoeRall** [comment]
@camitz No problem. Can you give my GitHub access to your app veyor account? I'll submit a pull request that'll contain the basic AppVeyor settings from cool whip.

**Comment by camitz** [comment]
Yes.

...how? :)

**Comment by JoeRall** [comment]
I've never done this before, but I think this should work. 

Go to the top and select team:

![image](https://cloud.githubusercontent.com/assets/1762141/11372308/a2a575b0-929a-11e5-9e34-1d33d46b5ca2.png)

Then go to add Collaborators:

![image](https://cloud.githubusercontent.com/assets/1762141/11372326/c21071e8-929a-11e5-9d1b-c75d05b744bf.png)

Then use my e-mail: Joseph.Rall@Live.com

I should be able to then work on your projects and set things up. Hopefully :smile:

**Comment by camitz** [comment]
Done!

I'll see if I can set up the nuget link.

**Comment by JoeRall** [comment]
@camitz - You the man. I'm in. I should be able to do almost everything from here. I'm in a meeting now, but will hopefully be able to get to this today. We'll be able to automate everything once it's all setup

**Comment by camitz** [comment]
Sounds great! I'm looking forward to seeing the result. At the moment I'm
just so lost, haha!

I'm sure you'll need some sort of nuget authorization so just let me know
how to do that.
